version: "3.3"

networks:
  pgsql:

configs:
  haproxy.cfg:
    file: ./haproxy.cfg

services:
  etcd1: &etcd
    image: quay.io/coreos/etcd:v3.2
    networks: [ pgsql ]
    environment:
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_INITIAL_CLUSTER: "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: supersecret
    hostname: etcd1
    command: etcd --name etcd1 --data-dir=/etcd-data --initial-advertise-peer-urls http://etcd1:2380 --advertise-client-urls http://etcd1:2379
    volumes:
      - /srv/etcd1-data:/etcd-data
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==astralinux-1"

  etcd2:
    <<: *etcd
    hostname: etcd2
    command: etcd --name etcd2 --data-dir=/etcd-data --initial-advertise-peer-urls http://etcd2:2380 --advertise-client-urls http://etcd1:2379
    volumes:
      - /srv/etcd2-data:/etcd-data
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==astralinux-2"

  etcd3:
    <<: *etcd
    hostname: etcd3
    command: etcd --name etcd3 --data-dir=/etcd-data --initial-advertise-peer-urls http://etcd3:2380 --advertise-client-urls http://etcd1:2379
    volumes:
      - /srv/etcd3-data:/etcd-data
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==astralinux-3"

  patroni1:
    image: kp11/patroni:latest
    networks: [ pgsql ]
    hostname: patroni1
    environment:
      PATRONI_NAME: patroni1
      PATRONI_RESTAPI_CONNECT_ADDRESS: patroni1:8008
      PATRONI_SCOPE: wsr
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: patroni1:5432
      PATRONI_POSTGRESQL_DATA_DIR: /db/data
    volumes:
      - /srv/pg1:/db/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==astralinux-1"
  
  patroni2:
    image: kp11/patroni:latest
    networks: [ pgsql ]
    hostname: patroni2
    environment:
      PATRONI_NAME: patroni2
      PATRONI_RESTAPI_CONNECT_ADDRESS: patroni2:8008
      PATRONI_SCOPE: wsr
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: patroni2:5432
      PATRONI_POSTGRESQL_DATA_DIR: /db/data
    volumes:
      - /srv/pg2:/db/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==astralinux-2"
    
  patroni3:
    image: kp11/patroni:latest
    networks: [ pgsql ]
    hostname: patroni3
    environment:
      PATRONI_NAME: patroni3
      PATRONI_RESTAPI_CONNECT_ADDRESS: patroni3:8008
      PATRONI_SCOPE: wsr
      PATRONI_POSTGRESQL_CONNECT_ADDRESS: patroni3:5432
      PATRONI_POSTGRESQL_DATA_DIR: /db/data
    volumes:
      - /srv/pg3:/db/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==astralinux-3"
  
  haproxy:
    image: haproxy:2.6-alpine
    networks: [ pgsql ]
    configs:
      - source: haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 5432:5432
      - 8404:8404